/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tool_delete_dd;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author levietloi
 */
public class delete_dd extends javax.swing.JFrame {

    /**
     * Creates new form delete_dd
     */
    public delete_dd() {
	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        txtPhoneNumber = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCustomer = new javax.swing.JTextField();
        txtPartner_Mc = new javax.swing.JTextField();
        btnDeleteCust = new javax.swing.JButton();
        btnDeleteUser = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Tool Cancel DD");
        setBackground(new java.awt.Color(255, 255, 102));
        setResizable(Boolean.FALSE);

        jLabel1.setText("Số Điện Thoại:");

        btnSearch.setText("Tìm kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PARTNER_MERCHANT_USER_ID", "CUSTOMER_ID", "MERCHANT_USER_ID", "LINK_REQUEST_ID", "LINK_STATUS", "LINKED_DATE", "MERCHANT_USER_TOKEN"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel2.setText("CUSTOMER_ID");

        jLabel3.setText("PARTNER_MERCHANT_USER_ID");

        btnDeleteCust.setText("Delete");
        btnDeleteCust.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCustActionPerformed(evt);
            }
        });

        btnDeleteUser.setText("Delete");
        btnDeleteUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btnSearch)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCustomer)
                            .addComponent(txtPartner_Mc, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDeleteCust)
                            .addComponent(btnDeleteUser))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteCust))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPartner_Mc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDeleteUser))
                .addContainerGap(182, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
	try {
	    // TODO add your handling code here:
	    Connection con =DriverManager.getConnection("jdbc:mysql://172.17.4.83:3306/vnp_o2o","fintech-loilv","97082a851f5e452a7fdcfbbf44cf4e88");

	    String phone_number = txtPhoneNumber.getText();
	    String sql = "SELECT * FROM CUSTOMER WHERE ";
	    if(phone_number.equals("")) {
		JOptionPane.showMessageDialog(rootPane,"Ban dang thieu thong tin so dien thoai","Alert",JOptionPane.WARNING_MESSAGE);
	    }
	    else {
		sql = sql + "CUST_MOB_NUMBER IN (" + phone_number + ") ";     
	    }
	    PreparedStatement st = (PreparedStatement) con
                    .prepareStatement
                    (sql);
	    ResultSet rs = st.executeQuery();
	    String customer_id = "0";
	    while (rs.next()) {	
		customer_id = customer_id + ", " +rs.getInt("CUSTOMER_ID");
//		String data[] = {rs.getString("M_BASE_TRANS_ID"), rs.getString("ORDER_ID"), rs.getString("ORDER_CODE"), rs.getString("SYS_SERVICE_CODE"), rs.getString("SYS_CODE"), rs.getString("SYS_OFFER_TRANS_CODE"), rs.getString("TRANS_AMOUNT"), rs.getString("TRANS_TYPE"), rs.getString("CAS_TRANS_DATETIME"), rs.getString("TRANS_DATETIME"), rs.getString("CREATE_TIME"), rs.getString("UPDATE_TIME"), rs.getString("TRANS_STATE"), rs.getString("TRANS_STATUS"), rs.getString("BGW_REQUEST_ID"), rs.getString("CFM_SERVICE_CODE")};
//		DefaultTableModel tbModel = (DefaultTableModel)jTable1.getModel();
//		tbModel.addRow(data);
	    }
	    String sql_dd = "SELECT * FROM PARTNER_MERCHANT_USER WHERE CUSTOMER_ID IN (" + customer_id + ")";
	    PreparedStatement st1 = (PreparedStatement) con
                    .prepareStatement
                    (sql_dd);
	    ResultSet rs1 = st1.executeQuery();
	    while(rs1.next()){
	    	String data[] = {rs1.getString("PARTNER_MERCHANT_USER_ID"), rs1.getString("CUSTOMER_ID"), rs1.getString("MERCHANT_USER_ID"), rs1.getString("LINK_REQUEST_ID"), rs1.getString("LINK_STATUS"), rs1.getString("LINKED_DATE"), rs1.getString("MERCHANT_USER_TOKEN")};
		DefaultTableModel tbModel = (DefaultTableModel)jTable1.getModel();
		tbModel.addRow(data);
	    }
	    con.close();   
	} catch (SQLException ex) {
//	    Logger.getLogger(My_Fist_Form.class.getName()).log(Level.SEVERE, null, ex);
//	    jTextArea1.append("Dang co loi xay ra: thieu thong tin tra cuu\n");
	}
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnDeleteCustActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCustActionPerformed
        // TODO add your handling code here:
	try {
	    // TODO add your handling code here:
	    Connection con =DriverManager.getConnection("jdbc:mysql://172.17.4.31:3306/vnp_o2o","fintech-loilv","97082a851f5e452a7fdcfbbf44cf4e88");

	    String customer_id = txtCustomer.getText();
	    String sql = "";
	    if(customer_id.equals("")) {
		JOptionPane.showMessageDialog(rootPane,"Ban dang thieu thong tin customer_id","Alert",JOptionPane.WARNING_MESSAGE);
	    }
	    else {
		sql = "DELETE FROM PARTNER_MERCHANT_USER WHERE CUSTOMER_ID IN (" + customer_id + ")";
	    }
	    int flag = 1;
	    if(!((txtCustomer.getText()).equals(""))){
		flag = JOptionPane.showConfirmDialog(rootPane, "Ban dang muon huy lien ket co CUSTOMER_ID: "+ txtCustomer.getText() , "Confirm Backup", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
	    }
//	    else{
//		JOptionPane.showMessageDialog(rootPane, "Data order_code null", "ERROR",JOptionPane.ERROR_MESSAGE);
//	    }
	    if(flag == JOptionPane.YES_OPTION){
		PreparedStatement st = (PreparedStatement) con
                    .prepareStatement
                    (sql);
		int rs = st.executeUpdate();
		if(rs > 0) {	
		    JOptionPane.showMessageDialog(rootPane,"Ban da huy thanh cong LK DD co ma CUSTOMER_ID la" + customer_id, "Alert", JOptionPane.INFORMATION_MESSAGE);
		}
	    }
	    con.close();   
	} catch (SQLException ex) {
//	    Logger.getLogger(My_Fist_Form.class.getName()).log(Level.SEVERE, null, ex);
//	    jTextArea1.append("Dang co loi xay ra: thieu thong tin tra cuu\n");
	}
    }//GEN-LAST:event_btnDeleteCustActionPerformed

    private void btnDeleteUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteUserActionPerformed
        // TODO add your handling code here:
	JOptionPane.showMessageDialog(rootPane,"Hien tai chuc nang dang hoan thanh","Alert",JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnDeleteUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
	/* Set the Nimbus look and feel */
	//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
	/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
	 */
	try {
	    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
		if ("Nimbus".equals(info.getName())) {
		    javax.swing.UIManager.setLookAndFeel(info.getClassName());
		    break;
		}
	    }
	} catch (ClassNotFoundException ex) {
	    java.util.logging.Logger.getLogger(delete_dd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (InstantiationException ex) {
	    java.util.logging.Logger.getLogger(delete_dd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (IllegalAccessException ex) {
	    java.util.logging.Logger.getLogger(delete_dd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	} catch (javax.swing.UnsupportedLookAndFeelException ex) {
	    java.util.logging.Logger.getLogger(delete_dd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
	}
	//</editor-fold>

	/* Create and display the form */
	java.awt.EventQueue.invokeLater(new Runnable() {
	    public void run() {
		new delete_dd().setVisible(true);
	    }
	});
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDeleteCust;
    private javax.swing.JButton btnDeleteUser;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtCustomer;
    private javax.swing.JTextField txtPartner_Mc;
    private javax.swing.JTextField txtPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
