/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cancel_link_dd;

import java.awt.Color;
import java.awt.ComponentOrientation;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Cancel_Link_DD extends javax.swing.JFrame {

    /**
     * Creates new form Cancel_Link_DD
     */
    public Cancel_Link_DD() {
        initComponents();
        btnCancel.setEnabled(false);
        btnRefresh.setEnabled(false);
        btnRefresh.setBackground(Color.red);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtCustomerID = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        btnRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Phone Number:");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel2.setText("Customer_ID");

        btnCancel.setText("Cancal Link");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        txtLog.setColumns(20);
        txtLog.setRows(5);
        jScrollPane1.setViewportView(txtLog);

        btnRefresh.setBackground(new java.awt.Color(255, 255, 0));
        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, 395, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancel))))
                    .addComponent(btnRefresh, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCustomerID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRefresh)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        try{
            txtCustomerID.setText("");
            txtLog.setText("");
            Connection con =DriverManager.getConnection("jdbc:mysql://172.17.4.83:3306/vnp_o2o","fintech-loilv","97082a851f5e452a7fdcfbbf44cf4e88");

	    String phone_number = txtPhoneNumber.getText();
	    String sql = "SELECT * FROM CUSTOMER WHERE ";
	    if(phone_number.equals("")) {
		JOptionPane.showMessageDialog(rootPane,"Ban dang thieu thong tin so dien thoai","Alert",JOptionPane.WARNING_MESSAGE);
	    }
	    else {
		sql = sql + "CUST_MOB_NUMBER IN (" + phone_number + ") ";     
	    }
	    PreparedStatement st = (PreparedStatement) con
                    .prepareStatement
                    (sql);
	    ResultSet rs = st.executeQuery();
	    String customer_id = "0";
            
            txtLog.append("DANG TIM KIEM\n");
//            txtLog.setLineWrap(true);
//            txtLog.setText("DANG TIM KIEM\n");
            int i = 1;
	    while (rs.next()) {	
		customer_id = customer_id + ", " +rs.getInt("CUSTOMER_ID");
                txtLog.append(i + " : CUSTOMER_ID = " + rs.getInt("CUSTOMER_ID") + " , MOBILE = " + rs.getString("CUST_MOB_NUMBER") + ", NAME = " + rs.getString("CUSTOMER_NAME") + "\n");
                i++;
	    }
            System.out.println(customer_id);
            customer_id = customer_id.replace("0, ", "");
            txtCustomerID.setText(customer_id);
            btnCancel.setEnabled(true);
            con.close();   
        }
        catch(HeadlessException | SQLException e){
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        try {
	    // TODO add your handling code here:
	    Connection con =DriverManager.getConnection("jdbc:mysql://172.17.4.38:3306/vnp_o2o","fintech-loilv","97082a851f5e452a7fdcfbbf44cf4e88");

	    String customer_id = txtCustomerID.getText();
	    String sql = "";
	    if(customer_id.equals("")) {
		JOptionPane.showMessageDialog(rootPane,"Ban dang thieu thong tin customer_id","Alert",JOptionPane.WARNING_MESSAGE);
	    }
	    else {
		sql = "DELETE FROM PARTNER_MERCHANT_USER WHERE CUSTOMER_ID IN (" + customer_id + ")";
	    }
	    int flag = 1;
	    if(!((txtCustomerID.getText()).equals(""))){
		flag = JOptionPane.showConfirmDialog(rootPane, "Ban dang muon huy lien ket co CUSTOMER_ID: "+ txtCustomerID.getText() , "Confirm Backup", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
	    }
//	    else{
//		JOptionPane.showMessageDialog(rootPane, "Data order_code null", "ERROR",JOptionPane.ERROR_MESSAGE);
//	    }
	    if(flag == JOptionPane.YES_OPTION){
		PreparedStatement st = (PreparedStatement) con
                    .prepareStatement
                    (sql);
		int rs = st.executeUpdate();
		if(rs > 0) {	
		    JOptionPane.showMessageDialog(rootPane,"Ban da huy thanh cong LK DD co ma CUSTOMER_ID la" + customer_id, "Alert", JOptionPane.INFORMATION_MESSAGE);
                    txtLog.append("Ban da huy thanh cong LK DD co ma CUSTOMER_ID la" + customer_id);
		}
	    }
            btnSearch.setEnabled(false);
            btnCancel.setEnabled(false);
            btnRefresh.setEnabled(true);
	    con.close();   
	} catch (SQLException ex) {
//	    Logger.getLogger(My_Fist_Form.class.getName()).log(Level.SEVERE, null, ex);
//	    jTextArea1.append("Dang co loi xay ra: thieu thong tin tra cuu\n");
	}
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        txtPhoneNumber.setText("");
        txtCustomerID.setText("");
        txtLog.setText("");
        btnSearch.setEnabled(true);
        btnRefresh.setEnabled(false);
    }//GEN-LAST:event_btnRefreshActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cancel_Link_DD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cancel_Link_DD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cancel_Link_DD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cancel_Link_DD.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cancel_Link_DD().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtCustomerID;
    private javax.swing.JTextArea txtLog;
    private javax.swing.JTextField txtPhoneNumber;
    // End of variables declaration//GEN-END:variables
}
